### ISSUE TITLE
Please add Fedora 23

### ISSUE THREAD

**Issue by LinuxJedi** [numixproject/numix-copr#1]
Hi!

Since Fedora 23 is now released can you please add it to you Copr repo?

**Comment by sspreitzer** [comment]
+1

**Comment by fnkr** [comment]
+1

**Comment by sspreitzer** [comment]
Added builds from git: https://copr.fedoraproject.org/coprs/sspreitz/numix-git
```bash
$ dnf copr enable -y sspreitz/numix-git
$ dnf copr install -y numix-\*
```

**Comment by fnkr** [comment]
ping @satya164 Can you please rebuild this repo for Fedora 23?

**Comment by Foggalong** [comment]
We're working on it :)

**Comment by sspreitzer** [comment]
Please take a look at this repo for packaging:
https://github.com/sspreitzer/numix-specs

**Comment by satya164** [comment]
Hi, if someone wants to maintain the numix copr, I think we can talk about it. I'm short of time right now.

**Comment by sspreitzer** [comment]
Hi guys, I can take it over if you don't mind. I might release every two weeks on your git repo. I am currently also packaging the  numix plymouth theme for Fedora.

**Comment by satya164** [comment]
@sspreitzer Hey, awesome. Thanks a lot. Please ping me on Telegram @satya164

**Comment by Menubalk** [comment]
If I try to add the new repo I get an error, presumably because the repo has failed to build. Here´s the error log:

´´´
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/dnfpluginscore/lib.py", line 71, in urlopen
    librepo.download_url(url, fo.fileno(), handle)
  File "/usr/lib64/python3.4/site-packages/librepo/__init__.py", line 1517, in download_url
    return _librepo.download_url(handle, url, fd)
librepo.LibrepoException: (10, 'Status code: 404 for https://copr.fedoraproject.org/coprs/numix/numix/repo/epel-23/', 'Error HTTP/FTP status code')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/dnf-plugins/copr.py", line 264, in _download_repo
    f = dnfpluginscore.lib.urlopen(self, None, self.copr_url + api_path, 'w+')
  File "/usr/lib/python3.4/site-packages/dnfpluginscore/lib.py", line 73, in urlopen
    raise IOError(e.args[1])
OSError: Status code: 404 for https://copr.fedoraproject.org/coprs/numix/numix/repo/epel-23/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/dnf", line 57, in <module>
    main.user_main(sys.argv[1:], exit_code=True)
  File "/usr/lib/python3.4/site-packages/dnf/cli/main.py", line 174, in user_main
    errcode = main(args)
  File "/usr/lib/python3.4/site-packages/dnf/cli/main.py", line 60, in main
    return _main(base, args)
  File "/usr/lib/python3.4/site-packages/dnf/cli/main.py", line 112, in _main
    cli.run()
  File "/usr/lib/python3.4/site-packages/dnf/cli/cli.py", line 1091, in run
    return self.command.run(self.base.extcmds)
  File "/usr/lib/python3.4/site-packages/dnf-plugins/copr.py", line 153, in run
    self._download_repo(project_name, repo_filename, chroot)
  File "/usr/lib/python3.4/site-packages/dnf-plugins/copr.py", line 272, in _download_repo
    res = urllib.request.urlopen(self.copr_url + "/coprs/" + project_name, 'w+')
  File "/usr/lib64/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.4/urllib/request.py", line 461, in open
    req = meth(req)
  File "/usr/lib64/python3.4/urllib/request.py", line 1112, in do_request_
    raise TypeError(msg)
TypeError: POST data should be bytes or an iterable of bytes. It cannot be of type str.
´´´

**Comment by sspreitzer** [comment]
In theory it should work. Can you please retry it? I think the copr guys had a maintenance going on.

**Comment by sspreitzer** [comment]
epel-23 anyway sounds wrong. must be some other problem. i am investigating this..

**Comment by Menubalk** [comment]
Still doesn't work. If you go to https://copr.fedoraproject.org/coprs/numix/numix/ and look at the right you'll see that the build state is 'failed'. Maybe that has something to do with it?

**Comment by sspreitzer** [comment]
The failed state is only referencing that the ppc64le arch has failed building. (No space left on device) Looks like the builder for ppc64le needs some love. The i386 and x86_64 archs have succeeded building (https://copr.fedoraproject.org/coprs/numix/numix/build/143388/).

It works for me, can you please double check? How did you install the repo and the numix packages?

```
[root@sspreitz ~]# dnf repolist|grep numix                                                                                                                                   
numix-numix               Copr repo for numix owned by numix                  24
[root@sspreitz ~]# dnf update --disablerepo=* --enablerepo=numix-numix
Last metadata expiration check performed 1 day, 7:12:56 ago on Sat Nov 28 09:18:26 2015.
Abhängigkeiten sind aufgelöst.
=============================================================================================================================================================================
 Paket                                           Arch                           Version                                            Paketquelle                         Größe
=============================================================================================================================================================================
Aktualisieren:
 numix-gtk-theme                                 noarch                         999-1447685887.git.fc22                            numix-numix                         149 k
 numix-icon-theme                                noarch                         999-1447685887.git.fc22                            numix-numix                         6.2 M
 numix-icon-theme-circle                         noarch                         999-1447685887.git.fc22                            numix-numix                         1.7 M
 numix-icon-theme-shine                          noarch                         999-1447685887.git.fc22                            numix-numix                         332 k
 numix-icon-theme-utouch                         noarch                         999-1447685887.git.fc22                            numix-numix                         1.1 M

Transaktionsübersicht
=============================================================================================================================================================================
Aktualisieren  5 Packages

Gesamte Downloadgröße: 9.5 M
Ist dies in Ordnung? [j/N] :y
Pakete werden heruntergeladen:
(1/5): numix-gtk-theme-999-1447685887.git.fc22.noarch.rpm                                                                                     85 kB/s | 149 kB     00:01    
(2/5): numix-icon-theme-shine-999-1447685887.git.fc22.noarch.rpm                                                                             213 kB/s | 332 kB     00:01    
(3/5): numix-icon-theme-circle-999-1447685887.git.fc22.noarch.rpm                                                                            396 kB/s | 1.7 MB     00:04    
(4/5): numix-icon-theme-utouch-999-1447685887.git.fc22.noarch.rpm                                                                            440 kB/s | 1.1 MB     00:02    
(5/5): numix-icon-theme-999-1447685887.git.fc22.noarch.rpm                                                                                   497 kB/s | 6.2 MB     00:12    
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Gesamt                                                                                                                                       757 kB/s | 9.5 MB     00:12     
Transaktionsüberprüfung wird ausgeführt
Transaktionsprüfung war erfolgreich.
Transaktion wird getestet
Transaktionstest war erfolgreich.
Transaktion wird ausgeführt
  Aktualisieren    : numix-icon-theme-utouch-999-1447685887.git.fc22.noarch                                                                                             1/10 
  Aktualisieren    : numix-icon-theme-shine-999-1447685887.git.fc22.noarch                                                                                              2/10 
  Aktualisieren    : numix-icon-theme-circle-999-1447685887.git.fc22.noarch                                                                                             3/10 
  Aktualisieren    : numix-icon-theme-999-1447685887.git.fc22.noarch                                                                                                    4/10 
  Aktualisieren    : numix-gtk-theme-999-1447685887.git.fc22.noarch                                                                                                     5/10 
  Aufräumen        : numix-icon-theme-utouch-999-1447605985.git.fc22.noarch                                                                                             6/10 
  Aufräumen        : numix-icon-theme-shine-999-1447605985.git.fc22.noarch                                                                                              7/10 
  Aufräumen        : numix-icon-theme-circle-999-1447605985.git.fc22.noarch                                                                                             8/10 
  Aufräumen        : numix-icon-theme-999-1447605985.git.fc22.noarch                                                                                                    9/10 
  Aufräumen        : numix-gtk-theme-999-1447605985.git.fc22.noarch                                                                                                    10/10 
  Überprüfung läuft: numix-gtk-theme-999-1447685887.git.fc22.noarch                                                                                                     1/10 
  Überprüfung läuft: numix-icon-theme-999-1447685887.git.fc22.noarch                                                                                                    2/10 
  Überprüfung läuft: numix-icon-theme-circle-999-1447685887.git.fc22.noarch                                                                                             3/10 
  Überprüfung läuft: numix-icon-theme-shine-999-1447685887.git.fc22.noarch                                                                                              4/10 
  Überprüfung läuft: numix-icon-theme-utouch-999-1447685887.git.fc22.noarch                                                                                             5/10 
  Überprüfung läuft: numix-icon-theme-utouch-999-1447605985.git.fc22.noarch                                                                                             6/10 
  Überprüfung läuft: numix-gtk-theme-999-1447605985.git.fc22.noarch                                                                                                     7/10 
  Überprüfung läuft: numix-icon-theme-999-1447605985.git.fc22.noarch                                                                                                    8/10 
  Überprüfung läuft: numix-icon-theme-circle-999-1447605985.git.fc22.noarch                                                                                             9/10 
  Überprüfung läuft: numix-icon-theme-shine-999-1447605985.git.fc22.noarch                                                                                             10/10 

Aktualisiert:
  numix-gtk-theme.noarch 999-1447685887.git.fc22          numix-icon-theme.noarch 999-1447685887.git.fc22          numix-icon-theme-circle.noarch 999-1447685887.git.fc22  
  numix-icon-theme-shine.noarch 999-1447685887.git.fc22   numix-icon-theme-utouch.noarch 999-1447685887.git.fc22  

Komplett!
```

**Comment by Menubalk** [comment]
I just do dnf copr enable numix/numix, and it keeps giving me the error I posted earlier. Tried it a few seconds ago as well.

**Comment by sspreitzer** [comment]
What OS are you using? Fedora 23? Looks like this could be a bug in the copr client.

**Comment by Menubalk** [comment]
Korora 23 (which is basically Fedora 23 with some extras).

**Comment by storrgie** [comment]
@sspreitzer why is this closed? I get 404 when trying to enable on Fedora 23.

**Comment by storrgie** [comment]
Oh it looks like @satya164 dropped his copr repos entirely... along with fedy being gone?

**Comment by sspreitzer** [comment]
The new copr is numix/numix. 
https://copr.fedorainfracloud.org/coprs/numix/numix/

**Comment by storrgie** [comment]
@sspreitzer Should consider dumping this repo, I was searching about a bit and wouldn't have located that without your response (thanks by the way).

**Comment by sspreitzer** [comment]
@satya164 Can we maybe archive this Git repo and/or point to the new one?
* https://github.com/numixproject/numix-specs

**Comment by satya164** [comment]
@sspreitzer <https://github.com/sspreitzer> You've the access.

Satyajit Sahoo
UX Designer
Behance Profile <https://www.behance.net/satyajitha28c7>

We're all stories, in the end. Just make it a good one, eh? — The Doctor,
Season 5, Episode 13.
